server:
  port: 4000 # koa server port

serverTap:
  http: http://localhost:4567/v1
  websocket: ws://localhost:4567/v1

bot:
  http: http://localhost:3000
  websocket: ws://localhost:3000

groupId: 
botId: 
whiteList: 
blackList: 

deathLog: false # need DeathMessages

serverName: Minecraft